const PERMISSIONS = Object.freeze([
  'VIEW_DASHBOARD',
  'VIEW_WARD_INFORMATION', 'VIEW_ELECTION_DATA', 'VIEW_WARD_UPDATES', 'VIEW_NOTIFICATIONS',
  'VIEW_HOUSES', 'CREATE_HOUSES', 'EDIT_HOUSES', 'DELETE_HOUSES',
  'VIEW_FAMILIES', 'CREATE_FAMILIES', 'EDIT_FAMILIES', 'DELETE_FAMILIES',
  'VIEW_CITIZENS', 'CREATE_CITIZENS', 'EDIT_CITIZENS', 'DELETE_CITIZENS',
  'VIEW_VOTERS', 'EDIT_VOTERS',
  'VIEW_COMPLAINTS', 'CREATE_COMPLAINTS', 'EDIT_COMPLAINTS', 'DELETE_COMPLAINTS', 'ASSIGN_COMPLAINTS',
  'VIEW_18PLUS', 'EDIT_18PLUS',
  'VIEW_BIRTHDAYS',
  'EXPORT_DATA',
  'VIEW_SCHEMES', 'CREATE_SCHEMES', 'EDIT_SCHEMES', 'DELETE_SCHEMES',
  'VIEW_DEATH_RECORDS', 'CREATE_DEATH_RECORDS',
  'VIEW_GOVERNMENT_VOTER_LISTS', 'CREATE_GOVERNMENT_VOTER_LISTS',
  'VIEW_STAFF', 'CREATE_STAFF', 'EDIT_STAFF', 'DELETE_STAFF',
  'VIEW_USERS', 'EDIT_USERS', 'DELETE_USERS',
  'VIEW_WARDS', 'CREATE_WARDS', 'EDIT_WARDS', 'DELETE_WARDS',
  'VIEW_AUDIT', 'VIEW_RECYCLE_BIN', 'RESTORE_RECYCLE_BIN',
  'VIEW_CHAT', 'SEND_CHAT', 'CREATE_CHAT_GROUP', 'MANAGE_CHAT_GROUP', 'CREATE_STAKEHOLDERS', 'EDIT_STAKEHOLDERS', 'DELETE_STAKEHOLDERS',
]);

const ALL_PERMISSIONS = [...PERMISSIONS];

const NAGARSEVAK_CORE = Object.freeze([
  'VIEW_DASHBOARD','VIEW_WARD_INFORMATION','VIEW_WARD_UPDATES','VIEW_NOTIFICATIONS',
  'VIEW_HOUSES','CREATE_HOUSES','EDIT_HOUSES','VIEW_FAMILIES','CREATE_FAMILIES','EDIT_FAMILIES',
  'VIEW_CITIZENS','CREATE_CITIZENS','EDIT_CITIZENS','VIEW_VOTERS','VIEW_COMPLAINTS','ASSIGN_COMPLAINTS','EDIT_COMPLAINTS',
  'VIEW_18PLUS','VIEW_BIRTHDAYS','EXPORT_DATA','VIEW_SCHEMES','VIEW_DEATH_RECORDS','CREATE_DEATH_RECORDS',
  'VIEW_CHAT','SEND_CHAT','VIEW_RECYCLE_BIN','RESTORE_RECYCLE_BIN','VIEW_USERS','VIEW_WARDS',
  'VIEW_ELECTION_DATA','VIEW_GOVERNMENT_VOTER_LISTS','CREATE_GOVERNMENT_VOTER_LISTS',
  'VIEW_STAFF','CREATE_STAFF','EDIT_STAFF','DELETE_STAFF'
]);

const EMPLOYEE_CORE = Object.freeze([
  'VIEW_DASHBOARD','VIEW_WARD_INFORMATION','VIEW_WARD_UPDATES','VIEW_NOTIFICATIONS',
  'VIEW_HOUSES','CREATE_HOUSES','EDIT_HOUSES','VIEW_FAMILIES','CREATE_FAMILIES','EDIT_FAMILIES',
  'VIEW_CITIZENS','CREATE_CITIZENS','EDIT_CITIZENS','VIEW_VOTERS','VIEW_COMPLAINTS','EDIT_COMPLAINTS',
  'VIEW_18PLUS','VIEW_BIRTHDAYS','EXPORT_DATA','VIEW_SCHEMES','VIEW_DEATH_RECORDS','CREATE_DEATH_RECORDS',
  'VIEW_CHAT','SEND_CHAT','VIEW_RECYCLE_BIN','RESTORE_RECYCLE_BIN','VIEW_WARDS',
  'VIEW_ELECTION_DATA','VIEW_GOVERNMENT_VOTER_LISTS'
]);

function normalisePermissions(value) {
  if (Array.isArray(value)) return [...new Set(value.filter(v => PERMISSIONS.includes(v)))];
  if (typeof value === 'string') {
    try { return normalisePermissions(JSON.parse(value)); } catch (_) { return []; }
  }
  return [];
}

function resolveFieldPermissions(roleName, stored) {
  const saved = normalisePermissions(stored);
  const core = roleName === 'NAGARSEVAK' ? NAGARSEVAK_CORE : roleName === 'EMPLOYEE' ? EMPLOYEE_CORE : [];
  const onlyLanding = !saved.length || (saved.length === 1 && saved[0] === 'VIEW_DASHBOARD');
  let permissions = onlyLanding ? [...core] : saved;
  if (roleName === 'EMPLOYEE') {
    permissions = permissions.filter((p) => !['VIEW_USERS','EDIT_USERS','DELETE_USERS','VIEW_STAFF','CREATE_STAFF','EDIT_STAFF','DELETE_STAFF'].includes(p));
  }
  if (['NAGARSEVAK','EMPLOYEE'].includes(roleName) && !permissions.includes('VIEW_DASHBOARD')) {
    permissions.push('VIEW_DASHBOARD');
  }
  return [...new Set(permissions)];
}

module.exports = { PERMISSIONS, ALL_PERMISSIONS, NAGARSEVAK_CORE, EMPLOYEE_CORE, normalisePermissions, resolveFieldPermissions };
