import React,{useEffect,useMemo,useState} from 'react';
import {api} from '../services/api';
import {Empty,ErrorBox,Field,Loading,Modal,PageHeader,StatusPill,Toolbar} from '../components/Ui';
import WardFilter from '../components/WardFilter';
import {useWardFilter} from '../wardFilter';
import {can} from '../rbac';

const statuses=['NOT_CONTACTED','CONTACTED','DOCUMENTS_PENDING','GUIDANCE_GIVEN','COMPLETED','OTHER'];
function eighteenthDate(dob){if(!dob)return null;const d=new Date(dob);return new Date(d.getFullYear()+18,d.getMonth(),d.getDate());}
function fmtDate(d){return d?new Intl.DateTimeFormat('en-IN',{dateStyle:'medium'}).format(new Date(d)):'—';}

export default function FollowUp18(){
 const {selectedWardId}=useWardFilter();const [days,setDays]=useState(90),[fromDays,setFromDays]=useState(0),[view,setView]=useState('upcoming');
 const [rows,setRows]=useState(null),[editing,setEditing]=useState(null),[selected,setSelected]=useState(null),[error,setError]=useState('');
 async function load(){try{setError('');setRows((await api.upcoming18(days,selectedWardId||undefined,fromDays)).data||[])}catch(e){setError(e.message);setRows([])}}
 useEffect(()=>{setRows(null);load()},[days,fromDays,selectedWardId]);
 const visible=useMemo(()=>{const all=rows||[];return view==='already'?all.filter(x=>x.daysTo18<=0):all.filter(x=>x.daysTo18>=0)},[rows,view]);

 async function save(e){e.preventDefault();try{await api.updatePerson(editing.person.id,{followupStatus:editing.person.followupStatus,followupDate:editing.person.followupDate,followupNotes:editing.person.followupNotes});setEditing(null);load()}catch(e){setError(e.message)}}

 return <div className="followup18-page"><PageHeader title="18+ Follow-up"/><ErrorBox error={error}/>
 <Toolbar><WardFilter/><select value={view} onChange={e=>{const v=e.target.value;setView(v);if(v==='upcoming'){setFromDays(0);setDays(90)}else{setFromDays(-15);setDays(0)}}}><option value="upcoming">Upcoming 18+</option><option value="already">Completed</option></select>{view==='upcoming'?<select value={days} onChange={e=>{setFromDays(0);setDays(Number(e.target.value))}}><option value={30}>Next 30 days</option><option value={60}>Next 60 days</option><option value={90}>Next 90 days</option><option value={180}>Next 180 days</option></select>:<select value={fromDays} onChange={e=>{const n=Number(e.target.value);setFromDays(n);setDays(0)}}><option value={-7}>Last 7 days</option><option value={-15}>Last 15 days</option><option value={-30}>Last 30 days</option><option value={-90}>Last 90 days</option></select>}</Toolbar>
 {!rows?<Loading/>:!visible.length?<Empty>{view==='already'?'No 18th birthdays were completed in the selected recent period.':'No upcoming 18th birthdays for this ward/range.'}</Empty>:<div className="panel table-wrap"><table><thead><tr><th>Citizen</th><th>18th date</th><th>Ward / Colony</th><th>Family</th><th>House / Address</th><th>Family members</th><th>Voter</th><th>Follow-up</th><th/></tr></thead><tbody>{visible.map(r=>{const p=r.person,f=p.family,h=f?.house,a=h?.area,w=a?.ward;return <tr key={p.id}><td data-label="Citizen"><strong>{p.fullName}</strong><div className="muted">DOB: {fmtDate(p.dob)}</div><div className="muted">Mobile: {p.mobile||'N/A'}</div></td><td data-label="18th date"><strong>{fmtDate(eighteenthDate(p.dob))}</strong><div className="muted">{r.daysTo18===0?'Today':r.daysTo18>0?`In ${r.daysTo18} days`:`Completed ${Math.abs(r.daysTo18)} days ago`}</div></td><td data-label="Ward / Colony">{w?.wardNumber||'N/A'}<div className="muted">{a?.name||'N/A'}</div></td><td data-label="Family">{f?.familyName||'N/A'}</td><td data-label="House / Address">{h?.houseNumber||'N/A'}<div className="muted">{h?.address||'N/A'}</div></td><td data-label="Family members"><div className="family-member-stack">{(f?.members||[]).map(m=><span key={m.id}>{m.fullName} · {m.mobile||'N/A'}</span>)}</div></td><td data-label="Voter">{p.voterProfile?.status==='VOTER'?'Voter':p.voterProfile?.status==='NON_VOTER'?'Non-Voter':'Not specified'}</td><td data-label="Follow-up"><StatusPill>{p.followupStatus||'NOT_CONTACTED'}</StatusPill></td><td data-label="Actions"><div className="card-actions"><button className="small-btn" onClick={()=>setSelected(r)}>View details</button>{can('EDIT_18PLUS')&&<button className="small-btn" onClick={()=>setEditing({person:p})}>Update</button>}</div></td></tr>})}</tbody></table></div>}
 {selected&&<Modal wide title={`18+ details · ${selected.person.fullName}`} onClose={()=>setSelected(null)}><div className="detail-grid">
  <div className="detail-card"><h3>Citizen</h3><p><b>Name:</b> {selected.person.fullName}</p><p><b>DOB:</b> {fmtDate(selected.person.dob)}</p><p><b>Age:</b> {selected.person.age??'N/A'}</p><p><b>Gender:</b> {selected.person.gender||'N/A'}</p><p><b>Mobile:</b> {selected.person.mobile||'N/A'}</p><p><b>Alternate:</b> {selected.person.alternateMobile||'N/A'}</p><p><b>Email:</b> {selected.person.email||'N/A'}</p></div>
  <div className="detail-card"><h3>Household</h3><p><b>Family:</b> {selected.person.family?.familyName||'N/A'}</p><p><b>House:</b> {selected.person.family?.house?.houseNumber||'N/A'}</p><p><b>Address:</b> {selected.person.family?.house?.address||'N/A'}</p><p><b>Landmark:</b> {selected.person.family?.house?.landmark||'N/A'}</p><p><b>Owner:</b> {selected.person.family?.house?.ownerName||'N/A'} · {selected.person.family?.house?.ownerMobile||'N/A'}</p></div>
  <div className="detail-card"><h3>Ward & colony</h3><p><b>Ward:</b> {selected.person.family?.house?.area?.ward?.wardNumber||'N/A'}{selected.person.family?.house?.area?.ward?.name?` · ${selected.person.family.house.area.ward.name}`:''}</p><p><b>Colony:</b> {selected.person.family?.house?.area?.name||'N/A'}</p><p><b>18th date:</b> {fmtDate(eighteenthDate(selected.person.dob))}</p><p><b>Voter status:</b> {selected.person.voterProfile?.status||'NOT_SPECIFIED'}</p><p><b>Voter ID:</b> {selected.person.voterProfile?.officialVoterIdRef||'N/A'}</p></div>
 </div><div className="detail-card"><h3>Complete family members</h3>{(selected.person.family?.members||[]).map(m=><p key={m.id}>{m.fullName} · {m.dob?fmtDate(m.dob):'DOB N/A'} · {m.mobile||'N/A'} · {m.age??'Age N/A'}</p>)}</div></Modal>}
 {editing&&<Modal wide title={`18+ follow-up · ${editing.person.fullName}`} onClose={()=>setEditing(null)}><div className="detail-card"><b>House:</b> {editing.person.family?.house?.houseNumber||'N/A'} · {editing.person.family?.house?.address||'N/A'}</div><form className="form-grid" onSubmit={save}><Field label="Follow-up status"><select value={editing.person.followupStatus||''} onChange={e=>setEditing({...editing,person:{...editing.person,followupStatus:e.target.value}})}><option value="">Select status</option>{statuses.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Follow-up date"><input type="date" value={editing.person.followupDate||''} onChange={e=>setEditing({...editing,person:{...editing.person,followupDate:e.target.value}})}/></Field><Field className="span-2" label="Notes"><textarea value={editing.person.followupNotes||''} onChange={e=>setEditing({...editing,person:{...editing.person,followupNotes:e.target.value}})}/></Field><div className="modal-actions span-2"><button type="button" className="ghost-btn" onClick={()=>setEditing(null)}>Cancel</button><button className="primary-btn">Save follow-up</button></div></form></Modal>}</div>
}
