import React,{useEffect,useState} from 'react';
import {api,getUser} from '../services/api';
import {isMaster} from '../rbac';
import {Empty,ErrorBox,Field,Loading,Modal,PageHeader,RowMenu,StatusPill} from '../components/Ui';
import PasswordResetModal from '../components/PasswordResetModal';
import PermissionEditor from '../components/PermissionEditor';

const blank = { name: '', email: '', mobile: '', password: '', status: 'ACTIVE', permissions: [], wardIds: [] };
export default function SubAdmins(){
 const user=getUser(),master=isMaster(user); const [rows,setRows]=useState(null),[wards,setWards]=useState([]),[error,setError]=useState(''),[edit,setEdit]=useState(null),[form,setForm]=useState(blank),[busy,setBusy]=useState(false),[detail,setDetail]=useState(null),[resetUser,setResetUser]=useState(null);
 useEffect(()=>{api.wards().then(r=>setWards(r.data||[])).catch(e=>setError(e.message))},[]);
 async function load(){try{setError('');setRows((await api.subAdmins()).data||[])}catch(e){setError(e.message);setRows([])}}
 useEffect(()=>{load()},[]);
 if(!master)return <div className="admin-data-page subadmins-page"><PageHeader title="Sub Master Admins" subtitle="This section is available only to the Master Admin."/><div className="empty">You do not have access to this section.</div></div>;
 async function save(e){e.preventDefault();setBusy(true);try{const d={name:form.name,email:form.email,mobile:form.mobile,password:form.password||undefined,status:form.status,permissions:form.permissions,wardIds:form.wardIds};if(edit==='create')await api.createSubAdmin(d);else await api.updateSubAdmin(edit.id,d);setEdit(null);await load();window.dispatchEvent(new CustomEvent('ward:permissions-updated'));window.dispatchEvent(new CustomEvent('ward:toast',{detail:{type:'success',message:'Sub Master Admin saved successfully.'}}));}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <div className="admin-data-page subadmins-page"><PageHeader title="Sub Master Admins" subtitle="Create additional admin accounts. Master Admin controls every permission and access setting." action={<button className="primary-btn" onClick={()=>{setForm({...blank});setEdit('create')}}>+ Create Sub Master Admin</button>}/><ErrorBox error={error}/>{rows===null?<Loading/>:!rows.length?<Empty>No Sub Master Admin accounts yet.</Empty>:<div className="panel table-wrap"><table><thead><tr><th>Admin</th><th>Login</th><th>Access</th><th>Wards</th><th>Permissions</th><th>Last login</th><th/></tr></thead><tbody>{rows.map(a=><tr key={a.id}><td data-label="Admin"><div className="cell-value"><strong>{a.name}</strong><div className="muted">Sub Master Admin</div></div></td><td data-label="Login"><div className="cell-value"><span>{a.email||'—'}</span><div className="muted">{a.mobile||'—'}</div></div></td><td data-label="Access"><div className="cell-value"><StatusPill>{a.status}</StatusPill></div></td><td data-label="Wards"><div className="cell-value">{(a.wardIds||[]).length?`${a.wardIds.length} assigned`:'None assigned'}</div></td><td data-label="Permissions"><div className="cell-value">{(a.permissions||[]).length} granted</div></td><td data-label="Last login"><div className="cell-value">{a.lastLoginAt?new Date(a.lastLoginAt).toLocaleString('en-IN'):'Never'}</div></td><td data-label="Actions"><RowMenu items={[
     {label:'View details',onClick:()=>setDetail(a)},
     {label:'Reset password',onClick:()=>setResetUser(a)},
     {label:'Edit',onClick:()=>{setForm({...blank,...a,password:''});setEdit(a)}}
    ]}/></td></tr>)}</tbody></table></div>}
 {edit&&<Modal wide title={edit==='create'?'Create Sub Master Admin':'Edit Sub Master Admin'} onClose={()=>setEdit(null)}><form id="sub-admin-form-v13" className="form-grid" onSubmit={save}><Field label="Full name"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Email / Login ID"><input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field><Field label="Mobile"><input required maxLength="10" value={form.mobile} onChange={e=>setForm({...form,mobile:e.target.value.replace(/\D/g,'').slice(0,10)})}/></Field><Field label={edit==='create'?'Password':'New password'}><input type="password" minLength="8" required={edit==='create'} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></Field><Field label="Account access"><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="ACTIVE">Active</option><option value="SUSPENDED">Suspended</option></select></Field><div className="span-2 ward-access-editor"><div className="permission-section-head"><strong>Ward access</strong><button type="button" className="small-btn" onClick={()=>setForm({...form,wardIds:form.wardIds?.length===wards.length?[]:wards.map(w=>w.id)})}>{form.wardIds?.length===wards.length?'Clear':'Select all wards'}</button></div><div className="ward-access-grid">{wards.map(w=><label key={w.id} className="ward-access-option"><input type="checkbox" checked={(form.wardIds||[]).includes(w.id)} onChange={e=>setForm({...form,wardIds:e.target.checked?[...(form.wardIds||[]),w.id]:(form.wardIds||[]).filter(id=>id!==w.id)})}/><span>{w.wardNumber}{w.name?` · ${w.name}`:''}</span></label>)}</div><small className="muted">This Sub Master Admin will see only the selected wards. No ward selected means no ward data access.</small></div></form><PermissionEditor role="SUB_MASTER_ADMIN" values={form.permissions||[]} onChange={v=>setForm({...form,permissions:v})} isMasterAdmin={true}/><div className="modal-actions"><button type="button" className="ghost-btn" onClick={()=>setEdit(null)}>Cancel</button><button form="sub-admin-form-v13" className="primary-btn" disabled={busy}>{busy?'Saving…':'Save Sub Master Admin'}</button></div></Modal>}
 {resetUser&&<PasswordResetModal user={resetUser} onClose={()=>setResetUser(null)} onSaved={load}/>}
 {detail&&<Modal title={`${detail.name} · Sub Master Admin`} onClose={()=>setDetail(null)}><div className="detail-grid"><div className="detail-card"><h3>Account</h3><p><b>Name:</b> {detail.name}</p><p><b>Email:</b> {detail.email||'N/A'}</p><p><b>Mobile:</b> {detail.mobile||'N/A'}</p><p><b>Status:</b> {detail.status}</p><p><b>Last login:</b> {detail.lastLoginAt?new Date(detail.lastLoginAt).toLocaleString('en-IN'):'Never'}</p></div><div className="detail-card"><h3>Access</h3><p><b>Wards:</b> {(detail.wardIds||[]).length?`${detail.wardIds.length} selected`:'None'}</p><p><b>Permissions:</b> {(detail.permissions||[]).length} granted</p><p><b>Ward list:</b> {(detail.wardIds||[]).length?(wards.filter(w=>(detail.wardIds||[]).includes(w.id)).map(w=>`${w.wardNumber}${w.name?` · ${w.name}`:''}`).join(', ')||'Selected wards'):'No ward access'}</p></div></div><div className="modal-actions"><button className="ghost-btn" onClick={()=>setDetail(null)}>Close</button></div></Modal>}</div>;
}
